name = "gcs-to-r2"
main = "src/worker.ts"
compatibility_date = "2023-09-25"

[vars]
AWS_DEFAULT_REGION = "asia-northeast1"
AWS_SERVICE = "s3"
AWS_S3_BUCKET_SCHEME = 'https:'
AWS_S3_BUCKET = "example-r2-migration.storage.googleapis.com"

[[r2_buckets]]
binding = 'R2'
bucket_name = 'example-gcs-migration'